apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
data:
  KAFKA_NUM_NETWORK_THREADS: "2"
  KAFKA_NUM_IO_THREADS: "8"
  KAFKA_SOCKET_SEND_BUFFER_BYTES: "102400"
  KAFKA_SOCKET_RECEIVE_BUFFER_BYTES: "102400"
  KAFKA_SOCKET_REQUEST_MAX_BYTES: "104857600"
  KAFKA_LOG_DIRS: "/kafka/logs"
  KAFKA_NUM_PARTITIONS: "2"
  KAFKA_NUM_REPLICAS: "2"
  KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "2"
  KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "2"
  KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
  KAFKA_LOG_RETENTION_HOURS: "168"
  KAFKA_LOG_SEGMENT_BYTES: "1073741824"
  KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: "300000"
  KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092"
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT"
  INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
  KAFKA_PORT: ""