apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service-db
  template:
    metadata:
      labels:
        app: auth-service-db
    spec:
      containers:
        - name: postgres
          image: postgres:16
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_DB
              value: "auth_db"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: pg-auth-storage
              mountPath: /var/lib/postgresql/data
          args:
            - "-c"
            - "wal_level=logical"
            - "-c"
            - "max_replication_slots=10"
            - "-c"
            - "max_wal_senders=10"
            - "-c"
            - "max_wal_size=2GB"
            - "-c"
            - "listen_addresses=*"
      volumes:
        - name: pg-auth-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
