apiVersion: v1
kind: Service
metadata:
  name: auth-service-db
  labels:
    app: postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: auth-service-db
  